### ISSUE TITLE
How to normalize the input of similarity subnet?

### ISSUE THREAD

**Issue by ksnzh** [msracver/Deep-Exemplar-based-Colorization#5]
Since the input is in range of 0 and 255, should it subtract the mean?
What is the mean value of  the data you trained for vgg gray?

Thanks.

**Comment by hmmlillian** [comment]
@ksnzh Since in our gray vgg19, "data" layer is followed by "data/bn" (Please refer to https://github.com/msracver/Deep-Exemplar-based-Colorization/blob/master/demo/models/similarity_subnet/vgg_19_gray_bn/deploy.prototxt), there's no need to subtract the mean. Thus, the mean value we used is (0, 0, 0).

**Comment by hmmlillian** [comment]
@ksnzh Yes, we implemented in this way.
